apiVersion: v1
kind: Service
metadata:
  name: support-app-service
  namespace: support-lab
spec:
  selector:
    app: support-app
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP
